[project]
name = "nuubot"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "monsterui>=1.0.46",
  "polars>=1.0",
  "pydantic>=2",
  "python-fasthtml>=0.14.4",
  "sqlalchemy>=2",
  "tabulate>=0.9",
  "websockets>=15.0.1",
]

[project.scripts]
nuubot-cli = "nuubot.cli:main"

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "notebook>=7.6.0",
    "playwright>=1.61.0",
]
