[runtime]
bot_id = 12
exec_network = "mainnet"
data_network = "mainnet"
max_loop = 20
loop_seconds = 1.0
min_timer_interval_ms = 1000

[market]
symbol = "BTC"
interval = "1m"

[[signalers]]
name = "startnow"
interval = "1m"
params = {}

[executor]
name = "tradebot"
take_profit_pct = 0.0
stop_loss_pct = 0.0
max_cycles = 0

[risk]
score = 1
